class Game(object):
    """docstring for Game"""
    def __init__(self, arg):
        super(Game, self).__init__()
        self.arg = arg

self._PK
self._ALGORITHMTYPE
self._CURRENTNUMBEROFPLAYERS
self._CURRENTPOSSESSION
self._CURRENTSEGMENT
self._EXTRAROTATIONS
self._FIXEDGOALIEROTATIONS
self._FLAGS
self._ISFINISHED
self._NUMBEROFPLAYERS
self._OPPOSINGTEAMSCORE
self._PLANNEDEXTRAMINUTES
self._PLANNEDGAMEMINUTES
self._PLANNEDHALFTIMEMINUTES
self._TEAMSCORE
self._TOTALROTATIONS
self._OPPOSINGSIDE
self._OPPOSINGTEAM
self._SETTINGS
self._SETTINGSGAME
self._TEAMEVENT
self._TEAMSIDE
self._ACTUALGAMEMINUTES
self._ACTUALHALFTIMEMINUTES
self._ACTUALSTOPPAGEMINUTES
self._CLOCKHALFTIMEDATE
self._CLOCKSTARTDATE
self._CLOCKSTOPDATE
self._EXTRALOGMINUTES
self._HALFLOGMINUTES
self._OPPOSINGPOSSESSIONMINUTES
self._OPPOSINGPOSSESSIONSTART
self._TEAMPOSSESSIONMINUTES
self._TEAMPOSSESSIONSTART
self._CURRENTFORMATION
self._EXTERNALID
self._FORMATION
self._OPPOSINGCOLORNAME
self._OPPOSINGTEAMNAME
