class TeamPlayer(object):
    """docstring for TeamPlayer"""
    def __init__(self, arg):
        super(TeamPlayer, self).__init__()
        self.arg = arg


self._PK
self._ISSAVED
self._PLAYERORDER
self._POSITIONPREFERENCE
self._PLAYER
self._TEAM
self._PLAYINGMINUTES
self._PLAYINGMINUTES1
self._PLAYINGMINUTES10
self._PLAYINGMINUTES11
self._PLAYINGMINUTES12
self._PLAYINGMINUTES13
self._PLAYINGMINUTES14
self._PLAYINGMINUTES15
self._PLAYINGMINUTES16
self._PLAYINGMINUTES17
self._PLAYINGMINUTES18
self._PLAYINGMINUTES19
self._PLAYINGMINUTES2
self._PLAYINGMINUTES20
self._PLAYINGMINUTES21
self._PLAYINGMINUTES3
self._PLAYINGMINUTES4
self._PLAYINGMINUTES5
self._PLAYINGMINUTES6
self._PLAYINGMINUTES7
self._PLAYINGMINUTES8
self._PLAYINGMINUTES9
self._TOTALMINUTES
self._ZONEMINUTES1
self._ZONEMINUTES2
self._ZONEMINUTES3
self._ZONEMINUTES4
self._ZONEMINUTES5
self._EXTERNALID
self._SHIRTNUMBER
self._THUMBNAILIMAGE
